# Convolutional Neural Networks (CNNs) with PyTorch
>  In this third chapter, we introduce convolutional neural networks, learning how to train them and how to use them to make predictions.

- toc: true 
- badges: true
- comments: true
- author: Lucas Nunes
- categories: [Datacamp]
- image: images/datacamp/___

> Note: This is a summary of the course's chapter 3 exercises "Introduction to Deep Learning with PyTorch" at datacamp. <br>[Github repo](https://github.com/lnunesAI/Datacamp/) / [Course link](https://www.datacamp.com/tracks/deep-learning-in-python)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (8, 8)

## Convolution operator

### Convolution operator - OOP way


<div class=""><p>Let's kick off this chapter by using convolution operator from the <code>torch.nn</code> package. You are going to create a random tensor which will represent your image and random filters to convolve the image with. Then you'll apply those images.  </p>
<p>The <code>torch</code> library and the <code>torch.nn</code> package have already been imported for you.</p></div>

Instructions
<ul>
<li>Create 10 images with shape <code>(1, 28, 28)</code>.</li>
<li>Build <code>6</code> convolutional filters of size <code>(3, 3)</code> with stride set to <code>1</code> and padding set to <code>1</code>.</li>
<li>Apply the filters in the image and print the shape of the feature map.</li>
</ul>

In [ ]:
# Create 10 random images of shape (1, 28, 28)
images = torch.rand(10, 1, 28, 28)

# Build 6 conv. filters
conv_filters = torch.nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, stride=1, padding=1)

# Convolve the image with the filters 
output_feature = conv_filters(images)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


### Convolution operator - Functional way

<div class=""><p>While I and most of PyTorch practitioners love the <code>torch.nn</code> package (OOP way), other practitioners prefer building neural network models in a more functional way, using <code>torch.nn.functional</code>. More importantly, it is possible to mix the concepts and use both libraries at the same time (we have already done it in the previous chapter). You are going to build the same neural network you built in the previous exercise, but this time using the functional way.  </p>
<p>As before, we have already imported the <code>torch</code> library and <code>torch.nn.functional</code> as <code>F</code>.</p></div>

Instructions
<ul>
<li>Create 10 random images with shape <code>(1, 28, 28)</code>. </li>
<li>Create 6 random filters with shape <code>(1, 3, 3)</code>.</li>
<li>Convolve the images with the filters.</li>
</ul>

In [ ]:
# Create 10 random images
image = torch.rand(10, 1, 28, 28)

# Create 6 filters
filters = torch.rand(6, 1, 3, 3)

# Convolve the image with the filters
output_feature = F.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


## Pooling operators

<p>Here you are going to practice using max-pooling in both OOP and functional way, and see for yourself that the produced results are the same. We have already created and printed the image for you, and imported <code>torch</code> library in addition to <code>torch.nn</code> and <code>torch.nn.Functional as F</code> packages.</p>

In [ ]:
im = torch.rand(1, 1, 6, 6)
im

tensor([[[[0.7989, 0.0204, 0.7930, 0.3497, 0.6119, 0.0206],
          [0.0638, 0.0222, 0.7317, 0.4015, 0.7412, 0.6715],
          [0.3570, 0.9558, 0.4519, 0.0878, 0.9475, 0.9259],
          [0.1232, 0.8895, 0.8213, 0.1246, 0.3500, 0.5687],
          [0.3768, 0.2558, 0.2215, 0.8291, 0.0138, 0.6400],
          [0.4323, 0.2306, 0.4451, 0.8640, 0.7037, 0.1160]]]])

Instructions
<ul>
<li>Build a max-pooling operator with size <code>2</code>.</li>
<li>Apply the max-pooling operator in the image (loaded as <code>im</code>).</li>
<li>Use a max-pooling operator in functional way in the image.</li>
<li>Print the results of both cases.</li>
</ul>

In [ ]:
# Build a pooling operator with size `2`.
max_pooling = torch.nn.MaxPool2d(2)

# Apply the pooling operator
output_feature = max_pooling(im)

# Use pooling operator in the image
output_feature_F = F.max_pool2d(im, 2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[0.7989, 0.7930, 0.7412],
          [0.9558, 0.8213, 0.9475],
          [0.4323, 0.8640, 0.7037]]]])
tensor([[[[0.7989, 0.7930, 0.7412],
          [0.9558, 0.8213, 0.9475],
          [0.4323, 0.8640, 0.7037]]]])


**You see how the results are the same. In general, torch.nn and torch.nn.functional are equivalent and the choice for one of them is mostly a personal choice.**

### Average-pooling operator

<p>After coding the max-pooling operator, you are now going to code the average-pooling operator. You just need to replace max-pooling with average pooling.</p>

Instructions
<ul>
<li>Build an average-pooling operator with size <code>2</code>.</li>
<li>Apply the average-pooling operator in the image.</li>
<li>Use an average-pooling operator in functional way in the image, called <code>im</code>.</li>
<li>Print the results of both cases.</li>
</ul>

In [ ]:
# Build a pooling operator with size `2`.
avg_pooling = torch.nn.AvgPool2d(2)

# Apply the pooling operator
output_feature = avg_pooling(im)

# Use pooling operator in the image
output_feature_F = F.avg_pool2d(im, 2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[0.2263, 0.5690, 0.5113],
          [0.5814, 0.3714, 0.6980],
          [0.3239, 0.5899, 0.3684]]]])
tensor([[[[0.2263, 0.5690, 0.5113],
          [0.5814, 0.3714, 0.6980],
          [0.3239, 0.5899, 0.3684]]]])


## Convolutional Neural Networks

### Your first CNN - __init__ method

<div class=""><p>You are going to build your first convolutional neural network. You're going to use the <code>MNIST</code> dataset as the dataset, which is made of handwritten digits from 0 to 9. The convolutional neural network is going to have 2 convolutional layers, each followed by a <code>ReLU</code> nonlinearity, and a fully connected layer. We have already imported <code>torch</code> and <code>torch.nn</code> as <code>nn</code>. Remember that each pooling layer halves both the height and the width of the image, so by using <code>2</code> pooling layers, the height and width are <code>1/4</code> of the original sizes. <code>MNIST</code> images have shape <code>(1, 28, 28)</code></p>
<p>For the moment, you are going to implement the <code>__init__</code> method of the net. In the next exercise, you will implement the <code>.forward()</code> method.</p>
<p><em>NB: We need <strong>2</strong> pooling layers, but we only need to <strong>instantiate a pooling layer once</strong>, because each pooling layer will have the same configuration. Instead, we will use <code>self.pool</code> twice in the next exercise.</em></p></div>

Instructions
<ul>
<li>Instantiate two convolutional filters: the first one should have <code>5</code> channels, while the second one should have <code>10</code> channels. The <code>kernel_size</code> for both of them should be <code>3</code>, and both should use <code>padding=1</code>. Use the names of the arguments (instead of using <code>1</code>, use <code>padding=1</code>).</li>
<li>Instantiate a <code>ReLU()</code> nonlinearity.</li>
<li>Instantiate a max pooling layer which halves the size of the image in both directions.</li>
<li>Instantiate a fully connected layer which connects the units with the number of classes (we are using <code>MNIST</code>, so there are <code>10</code> classes).</li>
</ul>

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate two convolutional layers
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU()
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(2, 2) 
        
        # Instantiate a fully connected layer
        self.fc = nn.Linear(7 * 7 * 10, 10)

### Your first CNN - forward() method

<div class=""><p>Now that you have declared all the parameters of your CNN, all you need to do is to implement the net's <code>forward()</code> method, and voila, you have your very first PyTorch CNN.</p>
<p>Note: for evaluation purposes, the entire code of the class needs to be in the script. We are using the <code>__init__</code> method as you have coded it on the previous exercise, while you are going to code the <code>.forward()</code> method here.</p></div>

Instructions
<ul>
<li>Apply the first <code>convolutional</code> layer, followed by the <code>relu</code> nonlinearity, then in the next line apply max-pooling layer.</li>
<li>Apply the second <code>convolutional</code> layer, followed by the <code>relu</code> nonlinearity, then in the next line apply max-pooling layer.</li>
<li>Transform the feature map from <code>4</code> dimensional to <code>2</code> dimensional space. The first dimension contains the batch size <code>(-1)</code>, deduct the second dimension, by multiplying the values for <code>height</code>, <code>width</code> and <code>depth</code>.</li>
<li>Apply the <code>fully-connected</code> layer and return the result.</li>
</ul>

In [ ]:
def forward(self, x):

    # Apply conv followd by relu, then in next line pool
    x = self.relu(self.conv1(x))
    x = self.pool(x)

    # Apply conv followd by relu, then in next line pool
    x = self.relu(self.conv2(x))
    x = self.pool(x)

    # Prepare the image for the fully connected layer
    x = x.view(-1, 7 * 7 * 10)

    # Apply the fully connected layer and return the result
    return self.fc(x)

## Training Convolutional Neural Networks

## Training CNNs

<p>Similarly to what you did in Chapter 2, you are going to train a neural network. This time however, you will train the CNN you built in the previous lesson, instead of a fully connected network. The packages you need have been imported for you and the network (called <code>net</code>) instantiated. The cross-entropy loss function (called <code>criterion</code>) and the Adam optimizer (called <code>optimizer</code>) are also available. We have subsampled the training set so that the training goes faster, and you are going to use a single epoch.</p>

In [ ]:
import torch.optim as optim
net = Net()
optimizer = optim.Adam(net.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()

In [ ]:
net.forward = forward.__get__(net)

In [ ]:
import torchvision
import torchvision.transforms as transforms

from six.moves import urllib
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0')]
urllib.request.install_opener(opener)

# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare the datasets
trainset = torchvision.datasets.MNIST('mnist', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, 
									  download=True, transform=transform)

# Prepare the dataloaders
train_loader = torch.utils.data.DataLoader(trainset, batch_size=1,
										  shuffle=True, num_workers=0)
test_loader = torch.utils.data.DataLoader(testset, batch_size=1,
										 shuffle=False, num_workers=0)       

Instructions
<ul>
<li>Compute the predictions from the <code>net</code>.</li>
<li>Using the <code>predictions</code> and the <code>labels</code>, compute the loss function.</li>
<li>Compute the gradients for each weight.</li>
<li>Update the weights using the <code>optimizer</code>.</li>
</ul>

In [ ]:
for i, data in enumerate(train_loader, 0):
    inputs, labels = data
    optimizer.zero_grad()

    # Compute the forward pass
    outputs = net(inputs)
        
    # Compute the loss function
    loss = criterion(outputs, labels)
        
    # Compute the gradients
    loss.backward()
    
    # Update the weights
    optimizer.step()

### Using CNNs to make predictions

<div class=""><p>Building and training neural networks is a very exciting job (trust me, I do it every day)! However, the main utility of neural networks is to make predictions. This is the entire reason why the field of deep learning has bloomed in the last few years, as neural networks predictions are extremely accurate. On this exercise, we are going to use the convolutional neural network you already trained in order to make predictions on the <code>MNIST</code> dataset.</p>
<p>Remember that <code>torch.max()</code> takes two arguments:
-<code>output.data</code> - the tensor which contains the data.</p>
<ul>
<li>Either <code>1</code> to do <code>argmax</code> or <code>0</code> to do <code>max</code>.</li>
</ul></div>

Instructions
<ul>
<li>Iterate over the given <code>test_loader</code>, saving the results of each iteration in <code>data</code>.</li>
<li>Get the image and label from the <code>data</code> tuple, storing the results in <code>image</code> and <code>label</code>.</li>
<li>Make a forward pass in the net using your <code>image</code>.</li>
<li>Get the net prediction using <code>torch.max()</code> function.</li>
</ul>

In [ ]:
net.eval()
# Iterate over the data in the test_loader
for i, data in enumerate(test_loader):
    # Get the image and label from data
    image, label = data
    
    # Make a forward pass in the net with your image
    output = net(image)
    
    # Argmax the results of the net
    _, predicted = torch.max(output.data, 1)
    
    if predicted == label: #all(predicted == label)
        print("Yipes, your net made the right prediction " + str(predicted))
    else:
        print("Your net prediction was " + str(predicted) + "\n    but the correct label is: " + str(label))

Yipes, your net made the right prediction tensor([7])
Yipes, your net made the right prediction tensor([2])
Yipes, your net made the right prediction tensor([1])
Yipes, your net made the right prediction tensor([0])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([1])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([9])
Your net prediction was tensor([6])
    but the correct label is: tensor([5])
Yipes, your net made the right prediction tensor([9])
Yipes, your net made the right prediction tensor([0])
Yipes, your net made the right prediction tensor([6])
