# Introduction to TensorFlow
>  Before you can build advanced models in TensorFlow 2, you will first need to understand the basics. In this chapter, you’ll learn how to define constants and variables, perform tensor addition and multiplication, and compute derivatives. Knowledge of linear algebra will be helpful, but not necessary.

- toc: true 
- badges: true
- comments: true
- author: Lucas Nunes
- categories: [Datacamp]
- image: images/datacamp/___

> Note: This is a summary of the course's chapter 1 exercises "Introduction to TensorFlow in Python" at datacamp. <br>[Github repo](https://github.com/lnunesAI/Datacamp/) / [Course link](https://www.datacamp.com/tracks/machine-learning-scientist-with-python)

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = (8, 8)
import tensorflow as tf

## Constants and variables

### Defining data as constants

<div class=""><p>Throughout this course, we will use <code>tensorflow</code> version 2.4 and will exclusively import the submodules needed to complete each exercise. This will usually be done for you, but you will do it in this exercise by importing <code>constant</code> from <code>tensorflow</code>.</p>
<p>After you have imported <code>constant</code>, you will use it to transform a <code>numpy</code> array, <code>credit_numpy</code>, into a <code>tensorflow</code> constant, <code>credit_constant</code>. This array contains feature columns from a dataset on credit card holders and is previewed in the image below. We will return to this dataset in later chapters.</p>
<p>Note that <code>tensorflow</code> 2 allows you to use data as either a <code>numpy</code> array or a <code>tensorflow</code> <code>constant</code> object. Using a <code>constant</code> will ensure that any operations performed with that object are done in <code>tensorflow</code>.  </p>
<p><img src="https://assets.datacamp.com/production/repositories/3953/datasets/10c0da730973582584bc227f4bca4b5510d42c9f/default_features.jpg" alt="This image shows four feature columns from a dataset on credit card default: education, marriage, age, and bill amount."></p></div>

In [2]:
df = pd.read_csv('https://github.com/lnunesAI/Datacamp/raw/main/2-machine-learning-scientist-with-python/14-introduction-to-tensorflow-in-python/datasets/uci_credit_card.csv')

In [8]:
credit_numpy = df[['EDUCATION', 'MARRIAGE', 'AGE', 'BILL_AMT1']].values

Instructions
<ul>
<li>Import the <code>constant</code> submodule from the <code>tensorflow</code> module.</li>
<li>Convert the <code>credit_numpy</code> array into a <code>constant</code> object in <code>tensorflow</code>. Do not set the data type.</li>
</ul>

In [15]:
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)


 The datatype is: <dtype: 'float64'>

 The shape is: (30000, 4)


**You now understand how constants are used in tensorflow. In the following exercise, you'll practice defining variables.**

### Defining variables

<div class=""><p>Unlike a constant, a variable's value can be modified. This will be useful when we want to train a model by updating its parameters.</p>
<p>Let's try defining and printing a variable. We'll then convert the variable to a <code>numpy</code> array, print again, and check for differences. Note that <code>Variable()</code>, which is used to create a variable tensor, has been imported from <code>tensorflow</code> and is available to use in the exercise.</p></div>

Instructions
<ul>
<li>Define a variable, <code>A1</code>, as the 1-dimensional tensor: [1, 2, 3, 4].</li>
<li>Apply <code>.numpy()</code> to <code>A1</code> and assign it to <code>B1</code>.</li>
</ul>

In [14]:
# Define the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

 B1:  [1 2 3 4]


**Did you notice any differences between the print statements for A1 and B1? In our next exercise, we'll review how to check the properties of a tensor after it is already defined.**

## Basic operations

<p>Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. This is because the operation multiplies elements in corresponding positions in the two tensors. An example of an element-wise multiplication, denoted by the <mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" role="presentation" tabindex="0" ctxtmenu_counter="2" style="font-size: 116.7%; position: relative;"><mjx-math class="MJX-TEX" aria-hidden="true"><mjx-mo class="mjx-n"><mjx-c class="mjx-c2299"></mjx-c></mjx-mo></mjx-math><mjx-assistive-mml role="presentation" unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML"><mo>⊙</mo></math></mjx-assistive-mml></mjx-container> symbol, is shown below:</p>

$$ \begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix} \odot \begin{bmatrix} 3 & 1 \\ 2 & 5 \end{bmatrix} = \begin{bmatrix} 3 & 2 \\ 4 & 5 \end{bmatrix} $$

<p>In this exercise, you will perform element-wise multiplication, paying careful attention to the shape of the tensors you multiply. Note that <code>multiply()</code>, <code>constant()</code>, and <code>ones_like()</code> have been imported for you.</p>

Instructions
<ul>
<li>Define the tensors <code>A1</code> and <code>A23</code> as constants.</li>
<li>Set <code>B1</code> to be a tensor of ones with the same shape as <code>A1</code>.</li>
<li>Set <code>B23</code> to be a tensor of ones with the same shape as <code>A23</code>.</li>
<li>Set <code>C1</code> and <code>C23</code> equal to the element-wise products of <code>A1</code> and <code>B1</code>, and <code>A23</code> and <code>B23</code>, respectively.</li>
</ul>

In [17]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = tf.ones_like(A1)
B23 = tf.ones_like(A23)

# Perform element-wise multiplication
C1 = tf.multiply(A1, B1)
C23 = tf.multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


**Notice how performing element-wise multiplication with tensors of ones leaves the original tensors unchanged.**

### Making predictions with matrix multiplication

<p>In later chapters, you will learn to train linear regression models. This process will yield a vector of parameters that can be multiplied by the input data to generate predictions. In this exercise, you will use input data, <code>features</code>, and a target vector, <code>bill</code>, which are taken from a credit card dataset we will use later in the course.</p>

$$ \text{features} = \begin{bmatrix} 2 & 24 \\ 2 & 26 \\ 2 & 57 \\ 1 & 37 \end{bmatrix}, 
\text{bill} = \begin{bmatrix} 3913 \\ 2682 \\ 8617 \\ 64400 \end{bmatrix}, \text{params} = \begin{bmatrix} 1000 \\ 150 \end{bmatrix} $$

<p>The matrix of input data, <code>features</code>, contains two columns: education level and age. The target vector, <code>bill</code>, is the size of the credit card borrower's bill. </p>

<p>Since we have not trained the model, you will enter a guess for the values of the parameter vector, <code>params</code>. You will then use <code>matmul()</code> to perform matrix multiplication of <code>features</code> by <code>params</code> to generate predictions, <code>billpred</code>, which you will compare with <code>bill</code>. Note that we have imported <code>matmul()</code> and <code>constant()</code>.</p>

In [22]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = tf.matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


**Understanding matrix multiplication will make things simpler when we start making predictions with linear models.**

### Summing over tensor dimensions

<p>You've been given a matrix, <code>wealth</code>. This contains the value of bond and stock wealth for five individuals in thousands of dollars.</p>

$$\text{wealth} = \begin{bmatrix} 11 & 50 \\ 7 & 2 \\ 4 & 60 \\ 3 & 0 \\ 25 & 10 \end{bmatrix} $$

<p>The first column corresponds to bonds and the second corresponds to stocks. Each row gives the bond and stock wealth for a single individual. Use <code>wealth</code>, <code>reduce_sum()</code>, and <code>.numpy()</code> to determine which statements are correct about <code>wealth</code>.</p>

Instructions
<pre>
Possible Answers

The individual in the first row has the highest total wealth (i.e. stocks + bonds).

Combined, the 5 individuals hold $50,000 in stocks.

<b>Combined, the 5 individuals hold \$50,000 in bonds.</b>

The individual in the second row has the lowest total wealth (i.e. stocks + bonds).

</pre>

In [23]:
wealth = tf.constant([[11, 50], [7, 2], [4, 60], [3, 0], [25, 10]])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([61,  9, 64,  3, 35], dtype=int32)>

In [34]:
tf.reduce_sum(wealth, 1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([61,  9, 64,  3, 35], dtype=int32)>

In [33]:
tf.reduce_sum(wealth, 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 50, 122], dtype=int32)>

**Understanding how to sum over tensor dimensions will be helpful when preparing datasets and training models.**

## Advanced operations

### Reshaping tensors

<div class=""><p>Later in the course, you will classify images of sign language letters using a neural network. In some cases, the network will take 1-dimensional tensors as inputs, but your data will come in the form of images, which will either be either 2- or 3-dimensional tensors, depending on whether they are grayscale or color images.</p>
<p>The figure below shows grayscale and color images of the sign language letter A. The two images have been imported for you and converted to the numpy arrays <code>gray_tensor</code> and <code>color_tensor</code>. Reshape these arrays into 1-dimensional vectors using the <code>reshape</code> operation, which has been imported for you from <code>tensorflow</code>. Note that the shape of <code>gray_tensor</code> is 28x28 and the shape of <code>color_tensor</code> is 28x28x3.</p>
<p><img src="https://assets.datacamp.com/production/repositories/3953/datasets/f5cd02c63926113b407c33b3f2f7f05c57d4f8b8/sign_1_10.jpg" alt="This figure shows grayscale and color images of the sign language letter &quot;A&quot;."></p></div>

In [52]:
!wget https://github.com/lnunesAI/Datacamp/raw/main/2-machine-learning-scientist-with-python/14-introduction-to-tensorflow-in-python/datasets/color_tensor.npz
!wget https://github.com/lnunesAI/Datacamp/raw/main/2-machine-learning-scientist-with-python/14-introduction-to-tensorflow-in-python/datasets/gray_tensor.npz

color_tensor = np.load('/content/color_tensor.npz')
gray_tensor = np.load('/content/gray_tensor.npz')
color_tensor = color_tensor.f.arr_0
gray_tensor = gray_tensor.f.arr_0

--2021-02-10 15:18:19--  https://github.com/lnunesAI/Datacamp/raw/main/2-machine-learning-scientist-with-python/14-introduction-to-tensorflow-in-python/datasets/color_tensor.npz
Resolving github.com (github.com)... 13.114.40.48
Connecting to github.com (github.com)|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/lnunesAI/Datacamp/main/2-machine-learning-scientist-with-python/14-introduction-to-tensorflow-in-python/datasets/color_tensor.npz [following]
--2021-02-10 15:18:19--  https://raw.githubusercontent.com/lnunesAI/Datacamp/main/2-machine-learning-scientist-with-python/14-introduction-to-tensorflow-in-python/datasets/color_tensor.npz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Lengt

Instructions
<ul>
<li>Reshape <code>gray_tensor</code> from a 28x28 matrix into a 784x1 vector named <code>gray_vector</code>.</li>
<li>Reshape <code>color_tensor</code> from a 28x28x3 tensor into a 2352x1 vector named <code>color_vector</code>.</li>
</ul>

In [54]:
# Reshape the grayscale image tensor into a vector
gray_vector = tf.reshape(gray_tensor, (28*28, 1))

# Reshape the color image tensor into a vector
color_vector = tf.reshape(color_tensor, (28*28*3, 1))

In [58]:
gray_vector.shape, color_vector.shape

(TensorShape([784, 1]), TensorShape([2352, 1]))

**Notice that there are 3 times as many elements in color_vector as there are in gray_vector, since color_tensor has 3 color channels.**

### Optimizing with gradients

<div class=""><p>You are given a loss function, <mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" role="presentation" tabindex="0" ctxtmenu_counter="8" style="font-size: 116.7%; position: relative;"><mjx-math class="MJX-TEX" aria-hidden="true"><mjx-mi class="mjx-i"><mjx-c class="mjx-c1D466 TEX-I"></mjx-c></mjx-mi><mjx-mo class="mjx-n" space="4"><mjx-c class="mjx-c3D"></mjx-c></mjx-mo><mjx-msup space="4"><mjx-mi class="mjx-i"><mjx-c class="mjx-c1D465 TEX-I"></mjx-c></mjx-mi><mjx-script style="vertical-align: 0.363em;"><mjx-texatom size="s" texclass="ORD"><mjx-mn class="mjx-n"><mjx-c class="mjx-c32"></mjx-c></mjx-mn></mjx-texatom></mjx-script></mjx-msup></mjx-math><mjx-assistive-mml role="presentation" unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>y</mi><mo>=</mo><msup><mi>x</mi><mrow><mn>2</mn></mrow></msup></math></mjx-assistive-mml></mjx-container>, which you want to minimize. You can do this by computing the slope using the <code>GradientTape()</code> operation at different values of <code>x</code>. If the slope is positive, you can decrease the loss by lowering <code>x</code>. If it is negative, you can decrease it by increasing <code>x</code>. This is how gradient descent works.</p>
<p><img src="https://assets.datacamp.com/production/repositories/3953/datasets/4a3d06616c28aed697d57914a26da3d831bac83c/gradient_plot.png" alt="The image shows a plot of y equals x squared. It also shows the gradient at x equals -1, x equals 0, and x equals 1."></p>
<p>In practice, you will use a high level <code>tensorflow</code> operation to perform gradient descent automatically. In this exercise, however, you will compute the slope at <code>x</code> values of -1, 1, and 0. The following operations are available: <code>GradientTape()</code>, <code>multiply()</code>, and <code>Variable()</code>.</p></div>

Instructions
<ul>
<li>Define <code>x</code> as a variable with the initial value <code>x0</code>.</li>
<li>Set the loss function, <code>y</code>, equal to <code>x</code> multiplied by <code>x</code>. Do not make use of operator overloading.</li>
<li>Set the function to return the gradient of <code>y</code> with respect to <code>x</code>.</li>
</ul>

In [62]:
def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = tf.Variable(x0)
	with tf.GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = tf.multiply(x, x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


**Notice that the slope is positive at x = 1, which means that we can lower the loss by reducing x. The slope is negative at x = -1, which means that we can lower the loss by increasing x. The slope at x = 0 is 0, which means that we cannot lower the loss by either increasing or decreasing x. This is because the loss is minimized at x = 0.**

### Working with image data

<div class=""><p>You are given a black-and-white image of a letter, which has been encoded as a tensor, <code>letter</code>. You want to determine whether the letter is an X or a K. You don't have a trained neural network, but you do have a simple model, <code>model</code>, which can be used to classify <code>letter</code>.</p>
<p>The 3x3 tensor, <code>letter</code>, and the 1x3 tensor, <code>model</code>, are available in the Python shell. You can determine whether <code>letter</code> is a K by multiplying <code>letter</code> by <code>model</code>, summing over the result, and then checking if it is equal to 1. As with more complicated models, such as neural networks, <code>model</code> is a collection of weights, arranged in a tensor.</p>
<p>Note that the functions <code>reshape()</code>, <code>matmul()</code>, and <code>reduce_sum()</code> have been imported from <code>tensorflow</code> and are available for use.</p></div>

In [64]:
letter = np.array([[1.0, 0, 1.0], [1., 1., 0], [1., 0, 1.] ])
model = np.array([[1., 0., -1.]])

Instructions
<ul>
<li>The model, <code>model</code>, is 1x3 tensor, but should be a 3x1. Reshape <code>model</code>.</li>
<li>Perform a matrix multiplication of the 3x3 tensor, <code>letter</code>, by the 3x1 tensor, <code>model</code>.</li>
<li>Sum over the resulting tensor, <code>output</code>, and assign this value to <code>prediction</code>.</li>
<li>Print <code>prediction</code> using the <code>.numpy()</code> method to determine whether <code>letter</code> is K.</li>
</ul>

In [68]:
# Reshape model from a 1x3 to a 3x1 tensor
model = tf.reshape(model, (3, 1))

# Multiply letter by model
output = tf.matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction =  tf.reduce_sum(output)
print(prediction.numpy())

1.0


**Your model found that prediction=1.0 and correctly classified the letter as a K. In the coming chapters, you will use data to train a model, model, and then combine this with matrix multiplication, matmul(letter, model), as we have done here, to make predictions about the classes of objects.**